import * as THREE from 'three';
import {
  DISC_SPEED, DISC_RADIUS, DISC_FORCE, DISC_HITBOX, DISC_HIT_MIN, DISC_HIT_MAX,
  DISC_HIT_GROW, EXPLOSION_FALLOFF_MULTIPLIER_DISC, EXPLOSION_COLLISION_MULTIPLIER,
  PULL_MULTIPLIER, ROCKET_AOE_DAMAGE,
} from '../config.js';
import type { ProjectileConfig } from './types.js';

export const DISC_CONFIG: ProjectileConfig = {
  name: 'disc',
  displayName: 'Disc',
  weaponType: 1,
  speed: DISC_SPEED,
  gravity: 0,
  explosionRadius: DISC_RADIUS,
  force: DISC_FORCE,
  forceMode: 'pull',
  bodyRadius: DISC_HITBOX,
  hitMin: DISC_HIT_MIN,
  hitMax: DISC_HIT_MAX,
  hitGrow: DISC_HIT_GROW,
  falloffMultiplier: EXPLOSION_FALLOFF_MULTIPLIER_DISC,
  collisionMultiplier: EXPLOSION_COLLISION_MULTIPLIER,
  forceMultiplier: PULL_MULTIPLIER,
  aoeDamage: ROCKET_AOE_DAMAGE,
  aoeRadius: DISC_RADIUS,
  damageColor: '#00ffff',
  trailColors: [
    new THREE.Color(0.0, 0.8, 1.0),
    new THREE.Color(0.0, 0.5, 0.9),
    new THREE.Color(0.0, 0.3, 0.7),
    new THREE.Color(0.2, 0.2, 0.5),
  ],
  trailParticlesPerUnit: 2,
  trailLifeMin: 0.8,
  trailLifeMax: 1.2,
  trailSpread: 0.2,
  trailForwardSpread: 0,
  trailParticleGravity: 0,
  trailOpacity: 0.5,
  trailBaseSize: 0.06,
  trailSizeRange: 0.15,
  trailScaleMin: 0.5,
  trailScaleMax: 1.5,
  trailRampIn: 0,
  meshColor: 0x00ffff,
  meshType: 'disc',
  glowShell: false,
  glowColor: 0xff4400,
  glowOpacity: 0.18,
  meshRampIn: false,
  meshRampInDuration: 0,
  meshStartScale: 1.0,
  terrainOffset: 0.2,
  needsServerTracking: false,
};
