import * as THREE from 'three';

import {
  GRAVITY, ROCKET_SPEED, ROCKET_RADIUS, ROCKET_BODY_RADIUS, ROCKET_FORCE,
  ROCKET_AOE_DAMAGE, ROCKET_AOE_RADIUS, HIT_MIN, HIT_MAX, HIT_GROW,
  EXPLOSION_FALLOFF_MULTIPLIER_ROCKET, KNOCKBACK_MULTIPLIER,
} from '../core/config.js';

import type { ProjectileConfig } from './types.js';

export const ROCKET_CONFIG: ProjectileConfig = {
  name: 'rocket',
  displayName: 'Rocket',
  weaponType: 0,
  speed: ROCKET_SPEED,
  gravity: GRAVITY,
  explosionRadius: ROCKET_RADIUS,
  force: ROCKET_FORCE,
  forceMode: 'push',
  bodyRadius: ROCKET_BODY_RADIUS,
  hitMin: HIT_MIN,
  hitMax: HIT_MAX,
  hitGrow: HIT_GROW,
  falloffMultiplier: EXPLOSION_FALLOFF_MULTIPLIER_ROCKET,
  collisionMultiplier: 1.0, // ball radius + explosion radius
  forceMultiplier: KNOCKBACK_MULTIPLIER,
  aoeDamage: ROCKET_AOE_DAMAGE,
  aoeRadius: ROCKET_AOE_RADIUS,
  damageColor: '#ffd700',
  trailColors: [
    new THREE.Color(1.0, 0.7, 0.1),
    new THREE.Color(1.0, 0.4, 0.0),
    new THREE.Color(0.8, 0.2, 0.1),
    new THREE.Color(0.5, 0.25, 0.2),
    new THREE.Color(0.35, 0.35, 0.4),
  ],
  trailParticlesPerUnit: 2,
  trailLifeMin: 1.2,
  trailLifeMax: 1.8,
  trailSpread: 0.25,
  trailForwardSpread: 0.2,
  trailParticleGravity: 0.02,
  trailOpacity: 0.4,
  trailBaseSize: 0.08,
  trailSizeRange: 0.25,
  trailScaleMin: 0.6,
  trailScaleMax: 1.8,
  trailRampIn: 0.1,
  meshColor: 0xffdd44,
  meshType: 'rocket',
  glowShell: true,
  glowColor: 0xff4400,
  glowOpacity: 0.18,
  glowScale: 0.8,
  meshRampIn: true,
  meshRampInDuration: 0.05,
  meshStartScale: 0.2,
  terrainOffset: HIT_MIN,
  needsServerTracking: true,
};
